export default [
    ['fish', '/models/fish.FBX'],
    ['frog', '/models/frog.FBX'],
    ['lizard', '/models/lizard.FBX'],
    ['pigeon', '/models/pigeon.FBX'],
    ['jackal', '/models/jackal.FBX'],
    ['dogScene', '/models/dog-scene.FBX'],
    ['dogBreathing', '/models/dog-panting.glb'],
    ['birdsScene', '/models/birds-scene.glb'],
    ['owl', '/models/owl.glb'],
    ['penguin', '/models/penguin.glb'],
    ['ostritch', '/models/ostritch.glb'],    
    
    ['batLimbsScene', '/models/limbs/bat-scene.glb'],
    ['whaleLimbsScene', '/models/limbs/whale-scene.glb'],
    ['horseLimbsScene', '/models/limbs/horse-scene.glb'],
    ['frogLimbsScene', '/models/limbs/frog-scene.glb'],
    ['owlLimbsScene', '/models/limbs/owl-scene.glb'],
    ['lionLimbsScene', '/models/limbs/lion-scene.glb'],
] as const;